
# This workflow runs datagen and commits changes
# to the repository.

name: datagen
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [17]    # Current Java LTS & minimum supported by Minecraft
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checking Out the Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checking Out FrozenLib
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: FrozenBlock/FrozenLib
          ref: master
          submodules: recursive
          path: FrozenLib
      - name: Validating the Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setting up Java ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          java-package: jdk
      - name: Setting Up the Gradle Wrapper
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Caching Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-#{{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Datagen
        run: ./gradlew runDatagen -PreleaseType=stable -PuseThirdPartyMods=false
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
