
# This workflow automatically adds the mod's .jar
# file to any release published to GitHub.

name: release
on:
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: 17    # Current Java LTS & minimum supported by Minecraft
        # and run on both Linux and Windows
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checking Out the Repository
        uses: actions/checkout@v3
      - name: Validating the Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setting up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          java-package: jdk
      - name: Setting Up the Gradle Wrapper
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Caching Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-#{{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Building
        run: ./gradlew build -PreleaseType=stable -PuseThirdPartyMods=false
      - name: Upload release to GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/*[0-9].jar
